[package]
name = "badsort"
version = "0.1.0"
authors = ["Andrew Todd <andrew123ast@outlook.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5"
